AllCops:
  NewCops: enable

  Exclude:
    - "vendor/**/*"
    - "node_modules/**/*"
    - "db/schema.rb"
    - "tmp/**/*"
    - "log/**/*"
    - "bin/**/*"
    - ".git/**/*"
    - "public/**/*"

require:
  - rubocop-rails
